package api

import "github.com/allentom/haruka"

func SetRouter(e *haruka.Engine) {
	e.Router.GET("/path/read", readDirHandler)
	e.Router.POST("/path/copy", copyFileHandler)
	e.Router.AddHandler("/path/remove", deleteFileHandler)
	e.Router.AddHandler("/path/rename", renameFileHandler)
	e.Router.AddHandler("/path/download", downloadFileHandler)
	e.Router.AddHandler("/path/chmod", chmodFileHandler)
	e.Router.AddHandler("/path/mkdir", createDirectoryHandler)
	e.Router.POST("/path/newFile", newTextFileHandler)
	e.Router.POST("/path/writeFile", writeFileHandler)
	e.Router.GET("/path/readFile", readAsTextFileHandler)
	e.Router.AddHandler("/task/search", newSearchFileTaskHandler)
	e.Router.AddHandler("/task/copy", newCopyFileTaskHandler)
	e.Router.AddHandler("/task/unarchive", newExtractTaskHandler)
	e.Router.AddHandler("/task/archive", newArchiveTaskHandler)
	e.Router.AddHandler("/task/delete", newDeleteTaskHandler)
	e.Router.AddHandler("/task/stop", stopTaskHandler)
	e.Router.AddHandler("/task/get", getTaskHandler)
	e.Router.AddHandler("/task/all", getTaskList)
	e.Router.POST("/mount/cifs", mountCifsHandler)
	e.Router.POST("/umount", umountHandler)
	e.Router.GET("/fstab/mounts", fstabMountListHandler)
	e.Router.POST("/fstab/mounts", fstabAddMountHandler)
	e.Router.DELETE("/fstab/mounts", fstabRemoveMountHandler)
	e.Router.GET("/fstab/reload", fstabReMountHandler)
	e.Router.GET("/info", readOSInfoDirHandler)
	e.Router.GET("/service/info", infoHandler)
	e.Router.GET("/files", getFileHandler)
	e.Router.GET("/thumbnails", getFileThumbnailHandler)
	e.Router.POST("/thumbnails/clear", clearThumbnailHandler)
	e.Router.POST("/user/auth", youPlusLoginHandler)
	e.Router.GET("/user/auth", youPlusLoginHandler)
	e.Router.AddHandler("/notification", notificationSocketHandler)
}
